namespace Evo
{
    /// <summary>
    /// Controls how random values are generated and how fitness of a <see cref="Genome"/> is calculated
    /// </summary>
    public interface IEvolutionInstructions
    {
        /// <summary>
        /// Use to create a custom fitness calculation
        /// </summary>
        /// <param name="genome">the genome to calculate fitness for</param>
        /// <returns>A value between 0 and 1 determining how fit to solve the proble the genome is.</returns>
        public float EvolutionFitnessFunction(Genome genome);

        /// <summary>
        /// Use to generate custom random values for the genomes
        /// </summary>
        /// <returns>a random value, of the type desired to be generated by the algorithm</returns>
        public object GetEvolutionRandomValue();
    }
}
